### ISSUE TITLE
Docker image digest SHA not valid in build.json

### ISSUE THREAD

**Issue by MaxWinterstein** [frenck/action-addon-linter#118]
As my addon is a little bit dirty made, I need to supply the image SHA in the `build.json`. Otherwise, the multi-arch builder uses the same base image for all arches. 

> Error: {'armhf': 'thomx/fr24feed-piaware:1.18.0@sha256:c21ad18c64a9d6d4f96706fe7504e0b762ecff01f5c71b00bff0a191c0857e14', 'armv7': 'thomx/fr24feed-piaware:1.18.0@sha256:f20d215e40f19dfad24d0f70c070fd89617f38335e82cd713b40c215e7ea2fac', 'aarch64': 'thomx/fr24feed-piaware:1.18.0@sha256:0bf6fb89e0fa983270c36fa8d953ea49b4c3d99a43ec5cc0b178bce7cd2712bc', 'amd64': 'thomx/fr24feed-piaware:1.18.0@sha256:44e5331926921285d6e33ad0bf5a51eea1fb63f2b5b52668591cece6f79bb9c4'} is not valid under any of the given schemas

Besides the ugliness of my addon, shouldn't the regex allow using images by its SHA?

**Comment by frenck** [comment]
This regex is adopted from Home Assistant 🤷‍♂️

**Comment by MaxWinterstein** [comment]
Seems like my initial problem that led to this issue can be solved another way - my mistake on that point. 

Well, this might be just a theoretical issue for a very small group of people - if someone else at all struggles with that at all. 

Feel free to close, I am no longer on need. 

Thx for all the other stuff you do 🫡
