### ISSUE TITLE
v2.17.0 errors out for `data` map type

### ISSUE THREAD

**Issue by jens-maus** [frenck/action-addon-linter#187]
Since version v2.17.0 the addon-linter returns with the following error:

```
Error: [{'type': 'data', 'read_only': False, 'path': '/usr/local'}, {'type': 'backup', 'read_only': False}] is not valid under any of the given schemas
```

I suspect this is due to the missing `data` type not being part of the newer map linter check added in v2.17.0. However, due to the addon config documentation, `data` is a valid map. See here:

![Bildschirmfoto 2024-09-30 um 08 43 26](https://github.com/user-attachments/assets/cf4cd6ef-6976-4770-8a2f-a939a5bbca97)

Thus, I think `data` is simply missing as a valid map type in the latest linter configs.

So please consider adding `data` for action-addon-linter to not complain for addons defining this map type. See here for an actual addon that uses/defines this map:

https://github.com/jens-maus/RaspberryMatic/blob/master/home-assistant-addon/config.yaml#L17-L22

Revertiing to v2.16.0 immediately solves the issue.

**Comment by frenck** [comment]
Thanks for report! That was indeed missed. Fix in https://github.com/frenck/action-addon-linter/releases/tag/v2.17.1
