### ISSUE TITLE
apparmor default really true?

### ISSUE THREAD

**Issue by jens-maus** [frenck/action-addon-linter#193]
Reading/comparing the official addon config.yaml documentation (https://developers.home-assistant.io/docs/add-ons/configuration/) with the defined default of action-addon-linter makes me wonder what the actual default for addons really is? According to the official HA Addon config documentation the default seems to be `apparmor: false` while here in the `config.schema.json` it is defined as true (https://github.com/frenck/action-addon-linter/blob/main/src/config.schema.json#L10).

So who is right?

**Comment by frenck** [comment]
It is defaulting to `true`, see also here: <https://github.com/home-assistant/supervisor/blob/d44e995aed60fc39c789529f70e79f17380a60a4/supervisor/addons/validate.py#L368>

**Comment by jens-maus** [comment]
> It is defaulting to `true`, see also here: https://github.com/home-assistant/supervisor/blob/d44e995aed60fc39c789529f70e79f17380a60a4/supervisor/addons/validate.py#L368

Thanks for checking back. Then I guess we need a documentation fix here ;-)
