### ISSUE TITLE
Error: 'IPC_LOCK' is not one of ...

### ISSUE THREAD

**Issue by jens-maus** [frenck/action-addon-linter#40]
Comparing the following two code passages, it seems action-addon-linter is incorrectly displaying an error in case an addon is specifying `IPC_LOCK` in the `privileged` section of its `config.json`: 

https://github.com/frenck/action-addon-linter/blob/7f0ae239e285121bcc3b53dca8ecee7f5281c742/src/config.schema.json#L182-L190

https://github.com/home-assistant/supervisor/blob/main/supervisor/docker/const.py#L8-L17

Or do I miss something regarding `IPC_LOCK` here?

**Comment by frenck** [comment]
Nope, you are not missing something, just missing in the validator :)
