### ISSUE TITLE
YAML Tab Error

### ISSUE THREAD

**Issue by MaxBec** [frenck/action-addon-linter#43]
Hey @frenck,

i just started to use your linter and got the following error. I don't know how to get rid of it:

```
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "diyhue/config.json", line 2, column 1
```

I tested it on this file:
https://github.com/MaxBec/hassio-diyHue/blob/master/diyhue/config.json

Here is the produced error output:
https://github.com/MaxBec/hassio-diyHue/runs/2225768951?check_suite_focus=true

Kind Regards,
Max

**Comment by frenck** [comment]
Yes, that is expected, tabs are problematic in our YAML world :)
(yeah even when its JSON, as we just convert that).

In general, everywhere in Home Assistant, don't use tabs 😄
